#!/home/samhaug/anaconda2/bin/python

import numpy as np
from scipy import signal
from sys import argv
import h5py
from matplotlib import pyplot as plt

def align(tr_list):
    align_list = []
    align_list.append(tr_list[0])

    for idx,ii in enumerate(tr_list[1::]):
        print ii.max()
        cor = signal.fftconvolve(tr_list[0],ii[::-1])
        midpoint = cor.shape[0]/2
        imax = np.argmax(cor)
        roll = -1*(midpoint-imax)
        align_list.append(np.roll(ii,roll))

    return align_list

h5file = argv[1]
a = h5py.File(h5file,'r')
tr_list = a['list'][...]
tr_list *= 1./tr_list.max(axis=1)[:,None]
align_list = align(tr_list)

'''
for idx, ii in enumerate(align_list):
    plt.plot(idx + ii,color='g',alpha=0.5)
    plt.plot(tr_list[idx] + idx,color='k',alpha=0.5)
plt.show()

#plt.plot(np.std(align_list,axis=0))
#plt.plot(np.std(tr_list,axis=0))
fig,ax = plt.subplots(2,1)
ax[0].plot(np.sum(align_list,axis=0),color='g')
ax[1].plot(np.sum(tr_list,axis=0))

fig1,ax1 = plt.subplots(2,1)
ax1[0].plot(np.std(align_list,axis=0),color='g')
ax1[1].plot(np.std(tr_list,axis=0))
plt.show()
'''

fig,ax = plt.subplots()
fig1,ax1 = plt.subplots()
ax.imshow(np.cov(align_list))
ax1.imshow(np.linalg.inv(np.cov(align_list)))
plt.show()
