#!/home/samhaug/anaconda2/bin/python

import h5py
import obspy
import numpy as np
import seispy
from matplotlib import pyplot as plt
import scipy

'''
Perform an inversion to get reflectivity throughout the mantle.
Need a path to data and a path to the greens functions saved in an h5 file
format.
'''


def data_setup(data_dir):
    start_time = -400
    print('data_setup')
    st_data = obspy.read(data_dir+'FJ_mask.pk')
    st_data = seispy.data.normalize_on_envelope(st_data,phase=['ScSScS'])
    for idx,tr in enumerate(st_data):
        st_data[idx].stats.location = st_data[idx].stats.sac['gcarc']
        o = tr.stats.sac['o']
        starttime = tr.stats.starttime
        st_data[idx] = seispy.data.phase_window(tr,['ScSScS'],window=(start_time,2050))
        st_data[idx].data += -1*st_data[idx].data.mean()
    st_data.interpolate(1)
    st_data = seispy.data.align_on_phase(st_data,phase=['ScSScS'],a_min=False)
    for idx,tr in enumerate(st_data):
        st_data[idx].stats.sac['o'] += -1*start_time
    st_data.sort(['location'])
    return st_data

def G_setup(f):
    d = {}
    names = []
    for ii in f.keys():
        d[float(ii)] = f[ii][...]
        names.append(float(ii))

    l = []
    names = np.array(sorted(names))
    for key in sorted(d):
        l.append(d[key])
    l = np.array(l)
    return l,names


data_dir = '/home/samhaug/work1/ScS_reverb_data/20160130/'
f = h5py.File('/home/samhaug/work1/ScS_reverb_sims/gf_reverb/FJ_20160130.h5','r')

l,names = G_setup(f)
G = l.T
st = data_setup(data_dir)
d = np.transpose([st[10].data])

print d.shape,G.shape
m = scipy.linalg.lstsq(G,d)

plt.scatter(names,m[0])
plt.plot(names,m[0])
plt.show()
plt.plot(np.dot(G,m[0]),color='r',alpha=0.5)
plt.plot(st[10].data,color='k',alpha=0.5)
plt.show()
#plt.imshow(l,aspect='auto')
#plt.show()







