#!/home/samhaug/anaconda2/bin/python

import numpy as np
import obspy
import h5py
import seispy
from obspy.taup import TauPyModel
from matplotlib import pyplot as plt

'''
Make glossary of reverberation waveforms to be used in migration.

Have the option of shifting all traces to align phase better.

Makes an h5py file with waveforms from 660 reverberations. Naming scheme:
tScS3 is a topside 660 reverberation for ScS3.
'''

def main():
    st = obspy.read('/home/samhaug/work1/ScS_reverb_sims/mineos/FJ_v3.0_h6/FJ_3.0_h6_d28/st_T.pk')
    st.filter('bandpass',freqmin=1/60.,freqmax=1/25.,zerophase=True)
    st.integrate().normalize()
    st = seispy.data.align_on_phase(st,phase=['ScSScS'])

    net = 'FJ'
    ev = '20160130'
    f = h5py.File('/home/samhaug/work1/ScS_reverb_sims/wave_glossary/'+net+'_'+ev+'_zero.h5','w')

    make_glossary(st[0],f)
    f.close()

def shift_stream(st,shift):
    '''
    Experiment with best temporal offset
    '''

    for idx,tr in enumerate(st):
        st[idx].data = np.roll(tr.data,shift)
    seispy.plot.simple_section(st,a_list=['S'])
    return st

def make_glossary(tr,h5file):

    model = TauPyModel(model='prem_3.0_10')

    def strip_phase(tr,phase,**kwargs):
        window = kwargs.get('window',[-20,140])
        shift = kwargs.get('shift',0)
        window[0] += shift
        window[1] += shift
        a = seispy.data.phase_window(tr,phase,window=window,model='prem_3.0_10')
        return a.data

    t = ['ScSScS',
         'ScSScSScS',
         'ScSScSScSScS']

    tr = seispy.data.tr_align_on_phase(tr,phase=[t[0]])
    h5file.create_dataset('bScS2',data=strip_phase(tr,[t[0]]))
    h5file.create_dataset('tScS2',data=-1*strip_phase(tr,[t[0]]))
    tr = seispy.data.tr_align_on_phase(tr,phase=[t[1]])
    h5file.create_dataset('bScS3',data=strip_phase(tr,[t[1]],shift=2))
    h5file.create_dataset('tScS3',data=-1*strip_phase(tr,[t[1]],shift=2))
    tr = seispy.data.tr_align_on_phase(tr,phase=[t[2]])
    h5file.create_dataset('bScS4',data=strip_phase(tr,[t[2]],shift=4))
    h5file.create_dataset('tScS4',data=-1*strip_phase(tr,[t[1]],shift=2))

main()









