#!/home/samhaug/anaconda2/bin/python

import numpy as np
from os import listdir

'''
Once you find an optimal perturbed model for explaining ScS_n traveltimes,
use this to make a Taup tvel file to predict traveltimes
'''

def read_mineos_vel(file_name):
    vel = np.genfromtxt(file_name,skip_header=3)
    vel = vel[:,0:4]
    vel *= 1/1000.
    vel[:,0] = 6371. - vel[:,0]
    vel = np.flipud(vel)
    vel = np.vstack((vel[:,0],vel[:,2],vel[:,3],vel[:,1])).T
    return vel

def write_taup(vel_array,fname):
    with open(fname,'w') as f:
        f.write('prem_model.tvel P\n')
        f.write('prem_model.tvel S\n')
        np.savetxt(f,vel_array,delimiter='   ',fmt='%0.4f')

vel = read_mineos_vel('./models/prem_noocean.txt')
write_taup(vel,'prem_3.0.tvel')
