#!/home/samhaug/anaconda2/bin/python

from sys import argv
import numpy as np
from scipy.interpolate import interp1d
from scipy.interpolate import UnivariateSpline
import scipy
from scipy.signal import gaussian
#from scipy.interpolate import CubicSpline
from matplotlib import pyplot as plt

'''
Smooth all discontinuities except the 660.
'''

def main():
    model = './models/noocean_notrans.txt'
    meta,cores,mantle = read_model(model)
    start = np.where(np.abs(mantle[:,0]-mantle[:,0].max()) == 220000)[0].max()
    stop = np.where(np.abs(mantle[:,0]-mantle[:,0].max()) == 670000)[0].max()
    print start,stop
    plt.plot(mantle[:,0],mantle[:,3])
    x = mantle[:,0]
    v = mantle[:,3]
    vmid = mantle[63:87,3]
    xmid = mantle[63:87,0]
    vnew = np.linspace(vmid[0],vmid[-1],num=len(vmid))
    xnew = np.linspace(xmid[0],xmid[-1],num=len(vmid))
    #plt.plot(x,v)
    #plt.plot(xmid,vmid)
    #plt.plot(xnew,vnew)
    z = np.polyfit(xmid,vmid,2)
    p = np.poly1d(z)
    #plt.plot(xnew,p(xnew))
    #plt.show()
    mantle[63:87,3] = p(xnew)
    mantle[63:87,7] = p(xnew)
    mantle[63:87,0] = xnew
    plt.plot(mantle[:,0],mantle[:,3])
    plt.show()
    out = np.vstack((cores,mantle))
    write_output(out,'smooth','smooth',title='smoothprem.txt')

def read_model(filename):
    a = open(filename)
    f = a.read()
    meta = f.strip().split('\n')[2].split()
    knots,nic,noc = meta[0],meta[1],meta[2]
    print noc
    a.close()
    model = np.genfromtxt(filename,skip_header=3)
    cores = model[0:int(noc),:]
    mantle = model[int(noc)::,:]
    return meta,cores,mantle

def write_output(out_array,discont,amp,**kwargs):
    title= kwargs.get('title','test.txt')
    with open(title, 'w') as f:
        f.write('Radius: {} m, Amplitude: {} %vs\n'.format(str(discont),
                str(amp)))
        f.write('1    1.0000   1\n')
        f.write('{}   {}   {}\n'.format(str(out_array.shape[0]),33,66))
        np.savetxt(f, out_array, delimiter="   ",fmt='%.1f')

main()
