#!/home/samhaug/anaconda2/bin/python

import h5py
import obspy
import numpy as np
import seispy
import scipy
from scipy.signal import tukey
from obspy.taup import TauPyModel
from matplotlib import pyplot as plt
from os import listdir
from scipy.signal import correlate

'''
Make greens functions for higher order reverberations by shifting the 660
km reverberation traveltimes.
'''

def find_reverb_times(tr,depth,model):
    '''
    Find traveltimes for top and bottomside reverberations at arbitrary depth.
    '''

    evdp = tr.stats.sac['evdp']
    gcarc = tr.stats.sac['gcarc']
    d = str(depth)

    bottomside = ['ScSScS',
                  'ScS^'+d+'ScS',
                  'sScS^'+d+'ScS',
                  'ScS^'+d+'ScSScS',
                  'sScS^'+d+'ScSScS',
                  'ScS^'+d+'ScSScSScS',
                  'sScS^'+d+'ScSScSScS']

    topside = ['ScSScS',
               'ScSSv'+d+'SScS',
               'sScSSv'+d+'SScS',
               'ScSSv'+d+'SScSScS',
               'sScSSv'+d+'SScSScS',
               'ScSSv'+d+'SScSScSScS',
               'sScSSv'+d+'SScSScSScS']

    bottomside_arr = model.get_travel_times(source_depth_in_km=evdp,
                                   distance_in_degree=gcarc,
                                   phase_list = bottomside)

    topside_arr = model.get_travel_times(source_depth_in_km=evdp,
                                   distance_in_degree=gcarc,
                                   phase_list = topside)

    return bottomside_arr,topside_arr

def strip_reverb(tr,depth,model):
    '''
    Use a tukey window to mask an axisem
    trace and only pass the reverberations
    '''
    sr = tr.stats.sampling_rate
    npts = tr.stats.npts
    masked_trace = tr.copy()
    b,t = find_reverb_times(tr,depth,model)
    o = tr.stats.sac['o']

    # Strip first bottom 660
    t1 = tukey(150,0.2)
    left = np.zeros(int(b[1].time+o)-100)
    right = np.zeros(npts-len(left)-len(t1))
    m1b = np.hstack((left,t1,right))

    # Strip second bottom 660
    t2 = tukey(150,0.2)
    left = np.zeros(int(b[3].time+o-20))
    right = np.zeros(npts-len(left)-len(t2))
    m2b = np.hstack((left,t2,right))

    # Strip second bottom 660
    t2 = tukey(150,0.2)
    left = np.zeros(int(b[5].time+o-20))
    right = np.zeros(npts-len(left)-len(t2))
    m3b = np.hstack((left,t2,right))

    # Strip first top 660
    t3 = tukey(150,0.2)
    left = np.zeros(int(t[1].time+o-20))
    right = np.zeros(npts-len(left)-len(t3))
    m1t = np.hstack((left,t3,right))

    # Strip second top 660
    t4 = tukey(150,0.2)
    left = np.zeros(int(t[3].time+o-20))
    right = np.zeros(npts-len(left)-len(t4))
    m2t = np.hstack((left,t4,right))


    plt.plot(m1b*tr.data,alpha=0.5)
    plt.plot(m2b*tr.data,alpha=0.5)
    plt.plot(m3b*tr.data,alpha=0.5)
    plt.plot(m1t*tr.data,alpha=0.5)
    plt.plot(m2t*tr.data,alpha=0.5)
    plt.plot(tr.data,alpha=0.5,color='k')
    plt.show()
    return b,t,[m1b*tr.data,m2b*tr.data,m3b*tr.data,m1t*tr.data,m2t*tr.data]

def data_setup(data_dir):
    start_time = -400
    print('data_setup')
    st_data = obspy.read(data_dir+'FJ_clean.pk')
    st_data = seispy.data.normalize_on_envelope(st_data,phase=['ScSScS'])
    for idx,tr in enumerate(st_data):
        st_data[idx].stats.location = st_data[idx].stats.sac['gcarc']
        o = tr.stats.sac['o']
        starttime = tr.stats.starttime
        st_data[idx] = seispy.data.phase_window(tr,['ScSScS'],window=(start_time,2050))
        st_data[idx].data += -1*st_data[idx].data.mean()
    st_data.interpolate(1)
    st_data = seispy.data.align_on_phase(st_data,phase=['ScSScS'],a_min=False)
    for idx,tr in enumerate(st_data):
        st_data[idx].stats.sac['o'] += -1*start_time
    st_data.sort(['location'])
    return st_data

def synth_setup(syn_dir,st_data):
    start_time = -400
    print('synth_setup')
    st_syn = obspy.read(syn_dir+'st_T.pk')
    st_syn.filter('bandpass',freqmax=1/25.,freqmin=1/60.)
    st_syn.integrate()
    st_syn = seispy.data.normalize_on_envelope(st_syn,phase=['ScSScS'])
    st_syn = seispy.data.align_on_phase(st_syn,phase=['ScSScS'],a_min=False)
    for idx,tr in enumerate(st_syn):
        st_syn[idx].stats.location = st_syn[idx].stats.sac['gcarc']
        st_syn[idx] = seispy.data.phase_window(tr,['ScSScS'],window=(start_time,2050))
        st_syn[idx].stats.starttime = st_data[idx].stats.starttime
        st_syn[idx].data += -1*st_syn[idx].data.mean()
        st_syn[idx].stats.sac['gcarc'] = st_data[idx].stats.sac['gcarc']
    st_syn.interpolate(1)
    st_syn = seispy.data.align_on_phase(st_syn,phase=['ScSScS'],a_min=False)
    for idx,tr in enumerate(st_syn):
        st_syn[idx].stats.sac['o'] += -1*start_time
    st_syn.sort(['location'])
    return st_syn

def align_synth_data(trd,trs):
    '''
    Align a synthetic with data based on max correlation.
    '''
    corr = scipy.signal.correlate(trd.data,trs.data,mode='same')
    shift = np.argmax(corr)-int(len(trs.data)/2.)
    trs.data = np.roll(trs.data,shift)
    return trs

def shift_greens(m1b,m2b,m3b,m1t,m2t,b660,t660,tr,depth,model):
    '''
    shift 660 reverb greens functions based on traveltime of
    specified depth reverberations.
    '''
    b660,t660 = find_reverb_times(tr,660,model)
    b,t = find_reverb_times(tr,depth,model)
    rm1b = seispy.data.roll_zero(m1b,int(b[1].time-b660[1].time))
    rm2b = seispy.data.roll_zero(m2b,int(b[3].time-b660[3].time))
    rm3b = seispy.data.roll_zero(m3b,int(b[5].time-b660[5].time))
    rm1t = seispy.data.roll_zero(m1t,int(t[1].time-t660[1].time))
    rm2t = seispy.data.roll_zero(m2t,int(t[3].time-t660[3].time))

    #plt.plot(m1b+m2b+m3b+m1t+m2t,alpha=0.5,color='b')
    #plt.plot(rm1b+rm2b+rm3b+rm1t+rm2t,alpha=0.5,color='r')
    #plt.plot(m1t+m2t,alpha=0.5,color='b')
    #plt.plot(rm1t+rm2t,alpha=0.5,color='r')
    #plt.show()

    return rm1b+rm2b+rm3b+rm1t+rm2t


data_dir = '/home/samhaug/work1/ScS_reverb_data/20160130/'
syn_dir = '/home/samhaug/work1/ScS_reverb_sims/mineos/FJ_v3.0_h6/FJ_3.0_h6_d28/'
model = TauPyModel(model='prem_3.0_10')

std = data_setup(data_dir)
sts = synth_setup(syn_dir,std)
#seispy.plot.plot(sts[10],phase_list=['ScS^660ScS'])

b660, t660, g  = strip_reverb(sts[10],660,model)

#plt.plot(g[0]+g[1]+g[2]+g[3]+g[4])

#3plt.plot(m1b660+m2b660+m1t660+m2t660,alpha=0.5)
#plt.show()
#shift_greens(g[0],g[1],g[2],g[3],g[4],b660,t660,sts[10],500,model)
#shift_greens(g[0],g[1],g[2],g[3],g[4],b660,t660,sts[10],400,model)
#shift_greens(g[0],g[1],g[2],g[3],g[4],b660,t660,sts[10],200,model)

'''
h5 = h5py.File('/home/samhaug/work1/ScS_reverb_sims/gf_reverb/FJ_20160130.h5','w')

for ii in np.arange(100,1000,100):
    print('writing '+str(ii))
    gf = shift_greens(g[0],g[1],g[2],g[3],g[4],b660,t660,sts[10],ii,model)
    h5.create_dataset(str(ii),data=gf)

h5.close()





'''






