#!/home/samhaug/anaconda2/bin/python

import numpy as np
import obspy
from matplotlib import pyplot as plt
import seispy

'''
Stack waveforms from group of traces to amplify reverberations
'''

def main():
    st = obspy.read('/home/samhaug/work1/ScS_reverb_data/20160130/FJ_clean.pk')
    sts = obspy.core.Stream()
    sts.append(st[0])

    data = []
    for idx,tr in enumerate(st):
        a = seispy.data.phase_window(tr,['ScSScS'],window=(-400,2050))
        data.append(a.data)
    sts[0].data = np.sum(data,axis=0)

    sts.write('/home/samhaug/work1/ScS_reverb_data/20160130/FJ_stack.pk',format='PICKLE')

main()
